### PR TITLE
Add optional App re-creation

### PR DESCRIPTION
**Pull request by stone-z**
Towards https://github.com/giantswarm/giantswarm/issues/31499
This PR:

- adds an optional pre-upgrade job that deletes an existing App CR instead of updating it in place.

### Checklist

- [x] Update changelog in CHANGELOG.md.
- [ ] Make sure `values.yaml` and `values.schema.json` are valid.

### CODE REVIEW

**Comment by stone-z** [comment]
This currently also bumps falco to 0.9.0, since I was testing it anyway

**Comment by fhielpos** [comment]
I have a couple of concerns about this:
1. This seems like a bit too dangerous and feels like it should be a platform feature instead.
2. I know sometimes this works as intended (deleting the app, re-creating it and everything just works). However, I feel there could be some edge cases where `chart-operator` could get stuck while deleting the chart and then trying to install it again.
3. This also means that every config change made to the bundle values would trigger the deletion and re-creation of the app, which in some environments could mean the app is constantly being created/deleted. Imagine gitops and this happening in multiple clusters at the time.

I know this has been motivated by the Falco changes in v0.9.0. I haven't checked it personally, but couldn't something have been done on the app side instead? 

Beside those points, happy to review the actual feature on Monday 😄

**Comment by stone-z** [comment]
>  1. This seems like a bit too dangerous and feels like it should be a platform feature instead.

I completely agree, but :upside_down_face: this is the boat we're in

>   2. I know sometimes this works as intended (deleting the app, re-creating it and everything just works). However, I feel there could be some edge cases where `chart-operator` could get stuck while deleting the chart and then trying to install it again.

Also agree, but short of re-implementing app platform or building something very heavyweight, I don't think we can account for them all. This does wait until the App CR is deleted

>   3. This also means that every config change made to the bundle values would trigger the deletion and re-creation of the app, which in some environments could mean the app is constantly being created/deleted. Imagine gitops and this happening in multiple clusters at the time.

I've tested that updating metadata of the user-values CM doesn't roll the app again. Changing the actual config of any app of course does. Do you know of cases where there is flapping config? That shouldn't be happening anyway

> I know this has been motivated by the Falco changes in v0.9.0. I haven't checked it personally, but couldn't something have been done on the app side instead?
 
When we dug into it before (also with Honeybadger), we thought it couldn't be done inside the app because Helm will enforce not changing immutable fields when it compares the "new" release to the "old" release. The release must actually be removed. I suppose we could have a pre-upgrade hook there that nukes its own chart, but that also seems risky.

> Beside those points, happy to review the actual feature on Monday 😄

Nah enjoy your P32 and we can talk about it on Tuesday. I have one other idea but I think it might mean spanning two releases. I noticed when starting to test this that the current Falco release actually doesn't run on v29, so there's at least a little time pressure, but I'm not married to this solution by any means

**Comment by stone-z** [comment]
I took deeper look and the only immutable fields in the immediate Falco issue are actually in Falco sidekick, so I'm thinking we can toggle sidekick off and on again via config during the upgrade. See the [tracking issue comment](https://github.com/giantswarm/giantswarm/issues/31499#issuecomment-2427651450)

**Pull request closed without merging**
